Middleware_ID: comp_modified
Upstreams:
  - peer_id: TesterUp_1
    addr: tcp://127.0.0.1:5550
    mode: connect  # option 'bind' or 'connect'
  - peer_id: TesterUp_2
    addr: tcp://127.0.0.1:5551
    mode: connect  # option 'bind' or 'connect'
Downstream:
  addr: tcp://127.0.0.1:5556
  mode: bind # option 'bind' or 'connect'
Tester:
  peer_nums: 10        # 或 n_down
  total_rounds: 5000      # 或 n_msg
